### ISSUE TITLE
Returns author, featured_image and terms arrays

### ISSUE THREAD

**Issue by otint** [nCrafts/json-rest-api-filter-fields#2]
Hi, plugin works to suppress fields but not arrays, for example, adding "&fields=ID,title" still returns the arrays for author, featured_image and terms. Is there a way to suppress the arrays, as well, unless included in the fields parameter? Otherwise, works really well, thanks!

**Comment by nCrafts** [comment]
This plugin uses a hook to filters out the un-wanted fields. Some info, like author, featured_image, etc ... is added to the output after the hook, so it can't be accessed. I am told the WP REST guys will be fixing this sometime.
